replicaCount: 1

image:
  repository: afarah1208/cast-service
  tag: "latest"

service:
  type: ClusterIP
  port: 8002
  targetPort: 8000

env:
  database_uri: cG9zdGdyZXNxbDovL2Nhc3RfZGJfdXNlcm5hbWU6Y2FzdF9kYl9wYXNzd29yZEBjYXN0X2RiL2Nhc3RfZGJfZGV2Cg==
