
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name {{ .Values.nginx.domain }};

        location /movies {
            proxy_pass http://movie-service:{{ .Values.movieService.port }};
        }

        location /casts {
            proxy_pass http://cast-service:{{ .Values.castService.port }};
        }
    }
