
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.castService.replicas }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: {{ .Values.castService.image }}:{{ .Values.tag | default "latest" }}
          ports:
            - containerPort: {{ .Values.castService.port }}
