
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  movieDbPassword: {{ .Values.movieDb.password | b64enc }}
  castDbPassword: {{ .Values.castDb.password | b64enc }}
