
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.movieService.port }}
