
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.castService.port }}
