
namespace: staging

movieService:
  image: afarah1208/movie-service
  replicas: 3
  port: 8001

castService:
  image: afarah1208/cast-service
  replicas: 3
  port: 8002

movieDb:
  image: postgres:13
  storageSize: 10Gi

castDb:
  image: postgres:13
  storageSize: 10Gi

nginx:
  replicas: 2
  domain: staging.jenkins.examen.cours-datascientest-aya.cloudns.ch
