apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: opaque
data:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  POSTGRES_DB: {{ .Values.db.name }}