image: nginx:latest

service:
  type: NodePort
  port: 80
  targetPort: 8081
  nodePort: 30080

configmap:
  nginx: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://movie_service:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast_service:8000/api/v1/casts;
      }
    }

autoscaling:
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
