apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: opaque
data:
  DATABASE_URI: {{ .Values.env.database_uri }}
  CAST_SERVICE_CAST_URL: {{ .Values.env.cast_service_host_url }}
